### ISSUE TITLE
'this' is undefined in template

### ISSUE THREAD

**Issue by PierBover** [wix/react-templates#141]
I'm trying out react-templates and the system works, as long as I don't include any JS expressions in the template.

On Test.rt
```html
<div>
	<h1>Hello templates</h1>
	<h2>{this.state.title}</h2>
</div>
```

And in Test.js
```js
import template from './Test.rt'
...
constructor(props){
	super(props)
	this.state = {
		title:"My title"
	}
}
render() {
	return template()
}
```

On Webpack config
```js
{ test: /\.rt/, loader: "react-templates-loader" }
```

On NPM package devDependencies:
```json
    "react-templates": "^0.5.2",
    "react-templates-loader": "^0.5.0",
```

When building I get:
![image](https://cloud.githubusercontent.com/assets/226483/15794741/db9b83b4-29b2-11e6-871b-0c7c94997e3a.png)

Am I missing something?

**Comment by PierBover** [comment]
I fixed it like this:

```
import React from 'react'

export default class Test extends React.Component {
	constructor(props){
		super(props)
		this.state = {
			titles:"Hello templates"
		}
	}
}

Test.prototype.render = require("./Test.rt");
```

Apparently it's some sort of ES6 Babel shenanigans...

**Comment by PierBover** [comment]
Even better:
```
import React from 'react'
import template from './Test.rt'

export default class Test extends React.Component {
...
}

Test.prototype.render = template
```

**Comment by PierBover** [comment]
Now this is the most elegant solution IMO

```js
import React from 'react'
import template from './Test.rt'

export default class Test extends React.Component {
...
	render(){
		return template.call(this)
	}
}
```

**Comment by nippur72** [comment]
Regarding your last point, it should be:
```js
render(){
   return template.bind(this)(); // instead of: return template().bind(this)
}
```
but that would be very inefficient because it creates a new binding on each render call. Anyway I don't think binding is necessary at all as React calls the `render` function with the correct binding to `this`. Indeed in my typescript code I just have:
```ts
class Test extends React.Component {
    render = require('test.rt');
}
```
BTW, a more elegant way might be having a `@decorator` e.g.:
```ts
@render(template)
class Test extends React.Component {
}
```
where `@render` is:
```ts
// @render decorator
export function template(fn) {
   return function(target) {
         target.prototype["render"] = fn; 
   }
}
```
Regarding your import statement:
```js
import template from './Test.rt'
```
if my understanding is correct, I think it should be
```js
import * as template from './Test.rt'
```
this because react templates does not export as `default` (I'm not sure, perhaps there's a Babel plugin that fixes that?)

**Comment by PierBover** [comment]
Hey @nippur72 thanks for the tips. I'm fairly new with React and ES6.

I will try and investigate the options you mention. From what you say, the `prototype` option sees the best as I believe it's not creating a binding every time.
```js
Test.prototype.render = template
```

Please, could anyone from the react-templates team chime in?

> this because react templates does not export as default (I'm not sure, perhaps there's a Babel plugin that fixes that?)

I think the modules are managed by Webpack...

**Comment by nippur72** [comment]
> I think the modules are managed by Webpack...

I was referring to the fact that (in theory) you can't have
```ts
import template from 'file';
```
unless `template` is exported like this:
```ts
export default function template() { ... }
```
But in react-templates, all functions are instead exported this way:
```ts
module.export = function template() { ... }
```
This means you can only import them with:
```ts
var template = require('file');
// or
import * as template from 'file';
```
But I suspect there is some babel plugin that is making `template` also available as `default` in your build chain. I can't say much more because I am not a babel user, just having heard of that. See for example:
- https://phabricator.babeljs.io/T2212
- https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by steezeburger** [comment]
`App.prototype.render = require('./index.rt.s')` was the only way I could get mine working. Any more word on this "issue"?

**Comment by nippur72** [comment]
@steezeburger if you use babel, that's the only way because class properties are not allowed (I don't know if there's a specific babel plugin for that).

**Comment by steezeburger** [comment]
Awesome, not a big deal for me. Still looks pretty clean. Thanks for the quick reply!
