### ISSUE TITLE
Forbid { expressions } in style attribute keys

### ISSUE THREAD

**Issue by nippur72** [wix/react-templates#145]
We should forbid the usage of `{}` within style keys, otherwise the user might be tempted to write something like this:
```html
<div rt-scope="'ground' as g">
	<span style="back{g}:red">Example</span>
</div>
```
which wrongly renders into:
```js
var templateRT = function () {
    function scopeG1() {
        var g = 'ground';
        return React.createElement('div', {}, React.createElement('span', { 'style': { backG: 'red' } }, 'Example'));
    }
    return scopeG1.apply(this, []);
};
```
(instead of `baground: red`)

**Comment by yotambarzilay** [comment]
Note that there are valid usage for {expressions} which should still be
supported, e.g.
style="backgound: {this.getBg()}"
style="{this.getStyle()}"
On Jun 6, 2016 7:33 PM, "nino-porcino" <notifications@github.com> wrote:

We should forbid the usage of {} within style keys, otherwise the user
might be tempted to write something like this:

<div rt-scope="'ground' as g">
    <span style="back{g}:red">Example</span>
</div>

which wrongly renders into:

var templateRT = function () {
    function scopeG1() {
        var g = 'ground';
        return React.createElement('div', {},
React.createElement('span', { 'style': { backG: 'red' } },
'Example'));
    }
    return scopeG1.apply(this, []);
};

(instead of baground: red)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wix/react-templates/issues/145>, or mute the thread
<https://github.com/notifications/unsubscribe/AGrDDOstVCR11VCIzUg3W2BwbJajoTynks5qJEvygaJpZM4IvFKd>
.

**Comment by nippur72** [comment]
@yotambarzilay yes, indeed the title says "style attribute keys", meaning you can't use in keys, but it's perfect legit to use in values (as in `background: {mycolor};`)

It might look superfluous to do this check, but there might be people coming from other frameworks that are accustomed to this practice (e.g. RiotJS), so better to display a proper error than ignore it.
