### ISSUE TITLE
Is there anything like 'rt-else'?

### ISSUE THREAD

**Issue by PierBover** [wix/react-templates#148]
Using `rt-if` we can render elements based on a condition.

Is there anything like `rt-else` to render something else if the condition is not met?

**Comment by nippur72** [comment]
no, there isn't, I guess because the resulting syntax would be not so intuitive. An hypothetical `rt-else` would have to refer to its upper sibiling node, which is unusual in HTML.  

When I have to write "else branches", I just use an if-not:
```html
<dif rt-if="cond()">then branch</div>
<dif rt-if="!cond()">else branch</div>
```
if you are concerned about the condition being evaluated twice (in case it's slow etc):
```html
<virtual rt-scope="cond() as c">
   <dif rt-if="c">then branch</div>
   <dif rt-if="!c">else branch</div>
</virtual>
```

**Comment by PierBover** [comment]
Thanks for the answer @nippur72 

> When I have to write "else branches", I just use an if-not

Yes, that what I ended up doing. It's not so bad for simple stuff.
