### ISSUE TITLE
Browserify build error

### ISSUE THREAD

**Issue by davenlin19** [wix/react-templates#186]
I've got an error: "Browserify Error: ParseError: Unexpected token" when building by Babel and Browserify. How could i fix that ? 

_**Hello.rc**_
`<div>Test</div>`
`^`
`ParseError: Unexpected token`

**_.babelrc_**
`{ "presets": ["es2015", "react"] }`

Thanks

**Comment by nippur72** [comment]
perhaps it's because of the missing `div` close? (`</div>`)

**Comment by davenlin19** [comment]
Sorry, i have the `div` close in my code. It's not the problem.

**Comment by nippur72** [comment]
I think you have some misconfiguration in your build pipeline, it's like you are trying to compile the `.rt` file as a JavaScript file. 

Don't know much of Browserify (I'm a Webpack guy), you have to make sure that `.rt` files are processed by react-templates and the result is added to the bundle.

Also, unless you use `--modules ES6`, the output from react-templates doesn't need to be transpiled because it's already ES5.

**Comment by davenlin19** [comment]
Thank you, by adding `transform: ['react-templatify']` into browserify's config. It works.
