### ISSUE TITLE
Using react-templates with EcmaScript 2015 (ES6) classes

### ISSUE THREAD

**Issue by KamilLelonek** [wix/react-templates#51]
My `footer.rt` looks as follows:

```HTML
<nav>
  <span className='current-year'>&copy; { this.currentYear() }</span>
</nav>
```

and `footer.js` is:

```JavaScript
import template from './footer.rt'

export default class extends React.Component {
  currentYear() {
    return new Date().getFullYear()
  }

  render() {
    return template()
  }
}
```

I get an error that `this` is `undefined` inside template. How to handle ES6 classes?

**Comment by danyshaanan** [comment]
Have you checked out the `--modules` option?
https://github.com/wix/react-templates/blob/gh-pages/docs/cli.md#options
(`rt --modules es6 ...`)

**Comment by KamilLelonek** [comment]
I'm using this with https://www.npmjs.com/package/react-templates-loader

**Comment by danyshaanan** [comment]
I do not know the react-templates-loader, but from what I can figure from [this file](https://github.com/AlexanderPavlenko/react-templates-loader/blob/master/index.js) it seems that you might be able to use the `modules` flag from the query string. If that does not work or does not fit your requirements, you'd probably need to propose the required change to @AlexanderPavlenko, or ask him to support the flag.

**Comment by KamilLelonek** [comment]
OK, then it's an issue of the loader. So you suggest to use:

```JavaScript
var options = queryString.parse(url.parse(this.query).query + '--modules es6');
```

?

**Comment by AlexanderPavlenko** [comment]
@KamilLelonek https://webpack.github.io/docs/using-loaders.html#query-parameters

**Comment by danyshaanan** [comment]
@KamilLelonek - no, `--module es6` is a command line flag, meant to be used when running webpack from the command line. (like in `webpack --module-bind "png=url-loader?mimetype=image/png"`). You should not edit the loader. As Alexander pointed out, the problem is not in his loader, as it accepts parameters as described in the webpack docs. Find the method you are using, and use the solution in the link.

**Comment by KamilLelonek** [comment]
It works without query parameters:

```javascript
render() {
  return template.apply(this);
}
```

**Comment by PierBover** [comment]
Ok, so we pass the es6 flag using query string in Webpack loaders config.

But how?

This doesn't work `{ test: /\.rt/, loader: "react-templates-loader?es6=true" }`.

Neither does this:
```
			{
				test: /\.rt/,
				loader: "react-templates-loader",
				query:{
					es6:true
				}
			}
```

Or this...

```
			{
				test: /\.rt/,
				loader: "react-templates-loader?es6",
				query:{
					modules: 'es6'
				}
			}
```
?

**Comment by PierBover** [comment]
Ok, it seems the proper way was:

```
			{
				test: /\.rt/,
				loader: "react-templates-loader?modules=es6"
			}
```

But now I get:
```
Uncaught SyntaxError: Unexpected token import
```

If I inspect the `build.js` from Webpack the import is there:
```
import { Modal } from './Modal';
```

**Comment by PierBover** [comment]
So I managed to send the output to Babel with this:

```
		loaders:[
			{
				test: /\.rt/,
				loader: "react-templates-loader?modules=es6"
			}
		],
		postLoaders:[
			{
				test: /\.jsx?$|.rt/,
				include: PATHS.app,
				loader:'babel',
				query: {
					presets: ['react', 'es2015']
				}
			}
		]
```

But I'm back at the error where React expects a string...

Can anyone can shed some light on how to do `rt-import`?

**Comment by nippur72** [comment]
When `es6=true` react-templates produces the following output:
```js
export default function () {
    return React.createElement('div', {});
}
```
this means that the render function can be imported into another es6 javascript source with:
```js
import Modal from './Modal';
```
Please note that this is different from:
```js
import { Modal } from './Modal';
```
Unfortunately the JavaScript syntax for modules is rather confusing because there are different ways of importing.

**Comment by PierBover** [comment]
Ok...

So how can I make `rt-import` work then? Is there any sample project using `rt-import`,webpack, and es6?

I either get the `Reacts expects a string` error, or the `Unexpected import token`.

**Comment by nippur72** [comment]
Can you please clarify what is `Modal` in your example? is it an `.rt` file? a `React.Component` ? a stateless function?

**Comment by PierBover** [comment]
Modal.jsx

```js
import React from 'react'
import template from './Modal.rt'

export default class Modal extends React.Component {
}

Modal.prototype.render = template
```

And Modal.rt

```html
<div class="modal">
	<div class="wrap">
		MODAL
	</div>
</div>
```

**Comment by nippur72** [comment]
The problem `Unexpected import token` is because the output from react-templates is not processed by babel.

I tried to setup a simple repo example here: https://github.com/nippur72/es6-webpack-example/ but I was not able to make it work correctly, so I kept the flag `modules=commonjs` for now. Unfortunately I'm not into babel, so I'm not good at setting a proper build chain.

If you want to try it, clone it and do `npm install`. Then run `webpack` and open the `index.html` from a web server (e.g. `hostr`). The example features a tag calling a tag with `rt-import`.

**Comment by PierBover** [comment]
Thanks a lot for your help @nippur72

I switched to `modules=commonjs` but I still get the errors

> Qarning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ModalNewBook`.warning @ build.js:8519

> build.js:8110 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ModalNewBook`.

**Comment by nippur72** [comment]
I got the same exact errors while making the build chain, so look at the example for reference.

Mostly it's:
1) `react` and/or `react-dom` not correctly imported (check it's `import { React }` vs `import React`)
2) `ReacDOM.render(el)` check the `el` argument, it must be created with `React.createElement()`.

**Comment by nippur72** [comment]
Update: I've figured out how to correctly chain `react-templates` to `babel` ! 

If you use `loaders` instead of `loader`, the specified loaders are chained, so it's simply:
```js
loaders: [ "babel-loader?presets[]=es2015", "react-templates-loader?modules=es6" ]
```

See the updated repo for a working example with `modules=es6`: 
https://github.com/nippur72/es6-webpack-example/

**Comment by PierBover** [comment]
I'm going to try this now!

@nippur72 I'll have to invite you to a coffee or beer some day!

**Comment by PierBover** [comment]
Ash...

The import works fine now, but whenever I use the imported component I get the same error. It's strange, the only significant difference from your project is I'm using `react-router`, otherwise they seem pretty similar.

So this works:
```
<rt-import name="Modal" from="./Modal"/>
<div>
	<h2>Hello Modal!</h2>
</div>
```

But this throws the same error:
```
<rt-import name="Modal" from="./Modal"/>
<Modal>
	<h2>Hello Modal!</h2>
</Modal>
```

> React.createElement: type should not be null, undefined, boolean, or number. etc

I will try to reduce the project to a minimum later today (or tomorrow) and if someone can take a look it would be awesome.

**Comment by nippur72** [comment]
it's 
```html
<rt-import name="default" as="Modal" from="./Modal" />
```
not 
```html
<rt-import name="Modal" from="./Modal" />
```
This because (I assume) you are exporting default in your `Modal.js` e.g.
```js
export default class Modal extends React.Component {
}
```

**Comment by PierBover** [comment]
YES!

**Comment by Blaumeiser** [comment]
Works for me, too!

webpack.config.js:
      test: /\.rt/,
      loaders: ["babel-loader?presets[]=es2015", "react-templates-loader?modules=es6"]
...
export default class CamAudioList extends React.Component {
...

<rt-import name="default" as="CamAudioList" from="./CamAudioList"/>
...
    <CamAudioList camBridge={this.props.chatcontrol.camBridge}/>
